version: '3'

# volumes:
#   postgres_data:
#       driver: local

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keycloak: 
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    restart: always
    ports: 
      - 8081:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    depends_on:
      - postgres