version: '3'

# volumes:
#   postgres_data:
#       driver: local

services:
  main-db:
    image: postgres
    container_name: main-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: alumni_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keycloak-db:
    image: postgres
    container_name: keycloak-db
    restart: always
    expose:
      - 5433
    ports:
      - 5433:5433
    command: -p 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keycloak: 
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    restart: always
    command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    ports: 
      - 8081:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_PORT: 5433
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./realm-export.json://opt/jboss/keycloak/imports/realm-export.json
    depends_on:
      - keycloak-db

  