spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alumni_db
    username: postgres
    password: postgres

  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: ${java.io.tmpdir}

server:
  port: 8080
  error:
    include-message: always

keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: alumni
  resource: alumni
  principal-attribute: preferred_username
